/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PartyMember = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const PartyData = IDL.Record({
  'members' : IDL.Vec(PartyMember),
  'leaderId' : IDL.Principal,
  'createdAt' : Timestamp,
  'partyId' : IDL.Text,
});
export const GuildChatMessage = IDL.Record({
  'text' : IDL.Text,
  'senderUsername' : IDL.Text,
  'senderPrincipal' : IDL.Text,
  'timestamp' : Timestamp,
});
export const GuildData = IDL.Record({
  'members' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text)),
  'leaderId' : IDL.Principal,
  'guildId' : IDL.Text,
  'chatMessages' : IDL.Vec(GuildChatMessage),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'maxMembers' : IDL.Nat,
});
export const Username = IDL.Text;
export const PlayerProfile = IDL.Record({
  'username' : Username,
  'class' : IDL.Text,
  'coins' : IDL.Nat,
  'equippedItems' : IDL.Vec(IDL.Text),
  'deaths' : IDL.Nat,
  'activeTitle' : IDL.Text,
  'pvpKills' : IDL.Nat,
  'level' : IDL.Nat,
  'totalPlaytime' : IDL.Nat,
  'monsterKills' : IDL.Nat,
  'lastZone' : IDL.Text,
});
export const CharacterClass = IDL.Text;
export const ChatMessage = IDL.Record({
  'text' : IDL.Text,
  'timestamp' : Timestamp,
});
export const EmoteType = IDL.Variant({
  'heart' : IDL.Null,
  'confused' : IDL.Null,
  'wave' : IDL.Null,
  'thumbsUp' : IDL.Null,
});
export const PlayerState = IDL.Record({
  'x' : IDL.Nat,
  'y' : IDL.Nat,
  'hp' : IDL.Nat,
  'mp' : IDL.Nat,
  'xp' : IDL.Nat,
  'maxHp' : IDL.Nat,
  'maxMp' : IDL.Nat,
  'questProgress' : IDL.Opt(IDL.Nat),
  'guildRank' : IDL.Opt(IDL.Text),
  'isWanted' : IDL.Opt(IDL.Bool),
  'activityScore' : IDL.Nat,
  'playerTitles' : IDL.Opt(IDL.Vec(IDL.Text)),
  'username' : Username,
  'lastDailyBonus' : IDL.Opt(Timestamp),
  'bountyAmount' : IDL.Opt(IDL.Nat),
  'inventoryItems' : IDL.Vec(IDL.Text),
  'equippedOffhand' : IDL.Opt(IDL.Text),
  'selectedClass' : CharacterClass,
  'guildId' : IDL.Opt(IDL.Text),
  'chatMessages' : IDL.Vec(ChatMessage),
  'coins' : IDL.Nat,
  'activeQuestId' : IDL.Opt(IDL.Text),
  'skillTree' : IDL.Opt(IDL.Text),
  'friendsList' : IDL.Opt(IDL.Vec(IDL.Text)),
  'craftedItems' : IDL.Opt(IDL.Vec(IDL.Text)),
  'deaths' : IDL.Opt(IDL.Nat),
  'activeTitle' : IDL.Opt(IDL.Text),
  'pvpKills' : IDL.Nat,
  'outfitColor' : IDL.Text,
  'level' : IDL.Nat,
  'discoveredZones' : IDL.Opt(IDL.Vec(IDL.Text)),
  'achievements' : IDL.Vec(IDL.Text),
  'totalPlaytime' : IDL.Opt(IDL.Nat),
  'emoteTimestamp' : Timestamp,
  'monsterKills' : IDL.Nat,
  'skillPoints' : IDL.Opt(IDL.Nat),
  'completedQuestIds' : IDL.Vec(IDL.Text),
  'outfitStyle' : IDL.Text,
  'potionCount' : IDL.Opt(IDL.Nat),
  'currentEmote' : IDL.Opt(EmoteType),
  'equippedArmor' : IDL.Opt(IDL.Text),
  'pvpKillsSession' : IDL.Opt(IDL.Nat),
  'characterId' : IDL.Nat,
  'hairColor' : IDL.Text,
  'lastActive' : Timestamp,
  'kills' : IDL.Nat,
  'respawnCity' : IDL.Opt(IDL.Text),
  'lastZone' : IDL.Opt(IDL.Text),
  'equippedWeapon' : IDL.Opt(IDL.Text),
  'partyId' : IDL.Opt(IDL.Text),
});
export const FriendStatus = IDL.Variant({
  'pending' : IDL.Null,
  'accepted' : IDL.Null,
});
export const FriendRecord = IDL.Record({
  'status' : FriendStatus,
  'username' : IDL.Text,
  'principalId' : IDL.Text,
});
export const GuildLeaderboardEntry = IDL.Record({
  'guildId' : IDL.Text,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'totalMemberLevels' : IDL.Nat,
  'totalKills' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'activityScore' : IDL.Nat,
  'characterClass' : IDL.Text,
  'username' : Username,
  'pvpKills' : IDL.Nat,
  'level' : IDL.Nat,
  'monsterKills' : IDL.Nat,
  'lastActive' : Timestamp,
});
export const PartyInvite = IDL.Record({
  'toPrincipal' : IDL.Principal,
  'fromPrincipal' : IDL.Text,
  'timestamp' : Timestamp,
  'fromUsername' : IDL.Text,
  'partyId' : IDL.Text,
});
export const PlayerSettings = IDL.Record({
  'weatherEffects' : IDL.Bool,
  'dayNightCycle' : IDL.Bool,
  'masterVolume' : IDL.Float64,
  'killStreaks' : IDL.Bool,
  'sfxVolume' : IDL.Float64,
  'musicVolume' : IDL.Float64,
  'particleQuality' : IDL.Text,
  'chatNotifications' : IDL.Bool,
  'damageNumbers' : IDL.Bool,
  'ambientSound' : IDL.Bool,
  'autoPickupGold' : IDL.Bool,
  'respawnCity' : IDL.Text,
  'smoothCamera' : IDL.Bool,
});
export const PlayerMessages = IDL.Record({
  'principal' : IDL.Principal,
  'username' : Username,
  'messages' : IDL.Vec(ChatMessage),
});
export const TradeLogEntry = IDL.Record({
  'offeredItemIds' : IDL.Vec(IDL.Text),
  'goldChange' : IDL.Int,
  'tradeId' : IDL.Text,
  'timestamp' : Timestamp,
  'receivedItemIds' : IDL.Vec(IDL.Text),
  'counterpartyUsername' : IDL.Text,
});
export const WhisperMessage = IDL.Record({
  'to' : IDL.Text,
  'from' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : Timestamp,
});
export const TradeOffer = IDL.Record({
  'principal' : IDL.Principal,
  'goldAmount' : IDL.Nat,
  'accepted' : IDL.Bool,
  'itemIds' : IDL.Vec(IDL.Text),
});
export const TradeSession = IDL.Record({
  'completedAt' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'offerA' : TradeOffer,
  'offerB' : TradeOffer,
  'tradeId' : IDL.Text,
});

export const idlService = IDL.Service({
  'acceptPartyInvite' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : PartyData, 'err' : IDL.Text })],
      [],
    ),
  'acceptTrade' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
  'applyPvpDamage' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Principal],
      [
        IDL.Record({
          'died' : IDL.Bool,
          'goldDropped' : IDL.Nat,
          'newHp' : IDL.Int,
          'xpLost' : IDL.Nat,
        }),
      ],
      [],
    ),
  'cancelTrade' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'checkNicknameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'claimDailyBonus' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'collectBounty' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'collectDroppedGold' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'completeQuest' : IDL.Func([IDL.Text], [], []),
  'createGuild' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : GuildData, 'err' : IDL.Text })],
      [],
    ),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
  'getAllPlayers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerState))],
      ['query'],
    ),
  'getCharacterCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getDiscoveredZones' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getFriendsList' : IDL.Func([], [IDL.Vec(FriendRecord)], []),
  'getGuild' : IDL.Func([IDL.Text], [IDL.Opt(GuildData)], ['query']),
  'getGuildByName' : IDL.Func([IDL.Text], [IDL.Opt(GuildData)], ['query']),
  'getGuildLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(GuildLeaderboardEntry)],
      ['query'],
    ),
  'getGuildMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(GuildChatMessage), 'err' : IDL.Text })],
      [],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getLeaderboardByLevelKills' : IDL.Func(
      [],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMyParty' : IDL.Func([], [IDL.Opt(PartyData)], []),
  'getOnlinePlayerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getPendingPartyInvite' : IDL.Func([], [IDL.Opt(PartyInvite)], []),
  'getPlayerAchievements' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getPlayerSettings' : IDL.Func([], [IDL.Opt(PlayerSettings)], []),
  'getRecentMessages' : IDL.Func([], [IDL.Vec(PlayerMessages)], ['query']),
  'getSkillTree' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
  'getTradeLog' : IDL.Func([], [IDL.Vec(TradeLogEntry)], []),
  'getWhispers' : IDL.Func([], [IDL.Vec(WhisperMessage)], []),
  'grantAchievement' : IDL.Func([IDL.Text], [], []),
  'grantTitle' : IDL.Func([IDL.Text], [], []),
  'initiateTrade' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : TradeSession, 'err' : IDL.Text })],
      [],
    ),
  'inviteToParty' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'leaveParty' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'loadPlayer' : IDL.Func([Username, CharacterClass], [PlayerState], []),
  'recordAttack' : IDL.Func([], [], []),
  'recordCraftedItem' : IDL.Func([IDL.Text], [], []),
  'recordMonsterKill' : IDL.Func([], [], []),
  'recordPlayerDeath' : IDL.Func([], [], []),
  'recordPvpKill' : IDL.Func(
      [],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'addedBounty' : IDL.Nat,
          'becameWanted' : IDL.Nat,
        }),
      ],
      [],
    ),
  'registerNickname' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeGuild' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'resetBountyOnSafeZone' : IDL.Func([], [], []),
  'saveActiveTitle' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
  'saveDiscoveredZones' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveEmote' : IDL.Func([EmoteType], [], []),
  'saveFriendsList' : IDL.Func([IDL.Vec(FriendRecord)], [], []),
  'saveGuildMembership' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'savePlayerAchievements' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'savePlayerClass' : IDL.Func([CharacterClass], [], []),
  'savePlayerCoins' : IDL.Func([IDL.Nat], [], []),
  'savePlayerEquipment' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'savePlayerHP' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'savePlayerInventory' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'savePlayerOutfit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'savePlayerPosition' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'savePlayerSettings' : IDL.Func([PlayerSettings], [], []),
  'savePlayerTitles' : IDL.Func([IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)], [], []),
  'savePlayerXP' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'savePotionCount' : IDL.Func([IDL.Nat], [], []),
  'saveQuestProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveRespawnCity' : IDL.Func([IDL.Text], [], []),
  'saveSkillTree' : IDL.Func([IDL.Text], [], []),
  'saveZoneAndPlaytime' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'sendChatMessage' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendGuildChat' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'sendWhisper' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'unlockAchievement' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateGuildMembers' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateTradeOffer' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PartyMember = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const PartyData = IDL.Record({
    'members' : IDL.Vec(PartyMember),
    'leaderId' : IDL.Principal,
    'createdAt' : Timestamp,
    'partyId' : IDL.Text,
  });
  const GuildChatMessage = IDL.Record({
    'text' : IDL.Text,
    'senderUsername' : IDL.Text,
    'senderPrincipal' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const GuildData = IDL.Record({
    'members' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text)),
    'leaderId' : IDL.Principal,
    'guildId' : IDL.Text,
    'chatMessages' : IDL.Vec(GuildChatMessage),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'maxMembers' : IDL.Nat,
  });
  const Username = IDL.Text;
  const PlayerProfile = IDL.Record({
    'username' : Username,
    'class' : IDL.Text,
    'coins' : IDL.Nat,
    'equippedItems' : IDL.Vec(IDL.Text),
    'deaths' : IDL.Nat,
    'activeTitle' : IDL.Text,
    'pvpKills' : IDL.Nat,
    'level' : IDL.Nat,
    'totalPlaytime' : IDL.Nat,
    'monsterKills' : IDL.Nat,
    'lastZone' : IDL.Text,
  });
  const CharacterClass = IDL.Text;
  const ChatMessage = IDL.Record({
    'text' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const EmoteType = IDL.Variant({
    'heart' : IDL.Null,
    'confused' : IDL.Null,
    'wave' : IDL.Null,
    'thumbsUp' : IDL.Null,
  });
  const PlayerState = IDL.Record({
    'x' : IDL.Nat,
    'y' : IDL.Nat,
    'hp' : IDL.Nat,
    'mp' : IDL.Nat,
    'xp' : IDL.Nat,
    'maxHp' : IDL.Nat,
    'maxMp' : IDL.Nat,
    'questProgress' : IDL.Opt(IDL.Nat),
    'guildRank' : IDL.Opt(IDL.Text),
    'isWanted' : IDL.Opt(IDL.Bool),
    'activityScore' : IDL.Nat,
    'playerTitles' : IDL.Opt(IDL.Vec(IDL.Text)),
    'username' : Username,
    'lastDailyBonus' : IDL.Opt(Timestamp),
    'bountyAmount' : IDL.Opt(IDL.Nat),
    'inventoryItems' : IDL.Vec(IDL.Text),
    'equippedOffhand' : IDL.Opt(IDL.Text),
    'selectedClass' : CharacterClass,
    'guildId' : IDL.Opt(IDL.Text),
    'chatMessages' : IDL.Vec(ChatMessage),
    'coins' : IDL.Nat,
    'activeQuestId' : IDL.Opt(IDL.Text),
    'skillTree' : IDL.Opt(IDL.Text),
    'friendsList' : IDL.Opt(IDL.Vec(IDL.Text)),
    'craftedItems' : IDL.Opt(IDL.Vec(IDL.Text)),
    'deaths' : IDL.Opt(IDL.Nat),
    'activeTitle' : IDL.Opt(IDL.Text),
    'pvpKills' : IDL.Nat,
    'outfitColor' : IDL.Text,
    'level' : IDL.Nat,
    'discoveredZones' : IDL.Opt(IDL.Vec(IDL.Text)),
    'achievements' : IDL.Vec(IDL.Text),
    'totalPlaytime' : IDL.Opt(IDL.Nat),
    'emoteTimestamp' : Timestamp,
    'monsterKills' : IDL.Nat,
    'skillPoints' : IDL.Opt(IDL.Nat),
    'completedQuestIds' : IDL.Vec(IDL.Text),
    'outfitStyle' : IDL.Text,
    'potionCount' : IDL.Opt(IDL.Nat),
    'currentEmote' : IDL.Opt(EmoteType),
    'equippedArmor' : IDL.Opt(IDL.Text),
    'pvpKillsSession' : IDL.Opt(IDL.Nat),
    'characterId' : IDL.Nat,
    'hairColor' : IDL.Text,
    'lastActive' : Timestamp,
    'kills' : IDL.Nat,
    'respawnCity' : IDL.Opt(IDL.Text),
    'lastZone' : IDL.Opt(IDL.Text),
    'equippedWeapon' : IDL.Opt(IDL.Text),
    'partyId' : IDL.Opt(IDL.Text),
  });
  const FriendStatus = IDL.Variant({
    'pending' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const FriendRecord = IDL.Record({
    'status' : FriendStatus,
    'username' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const GuildLeaderboardEntry = IDL.Record({
    'guildId' : IDL.Text,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'totalMemberLevels' : IDL.Nat,
    'totalKills' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'activityScore' : IDL.Nat,
    'characterClass' : IDL.Text,
    'username' : Username,
    'pvpKills' : IDL.Nat,
    'level' : IDL.Nat,
    'monsterKills' : IDL.Nat,
    'lastActive' : Timestamp,
  });
  const PartyInvite = IDL.Record({
    'toPrincipal' : IDL.Principal,
    'fromPrincipal' : IDL.Text,
    'timestamp' : Timestamp,
    'fromUsername' : IDL.Text,
    'partyId' : IDL.Text,
  });
  const PlayerSettings = IDL.Record({
    'weatherEffects' : IDL.Bool,
    'dayNightCycle' : IDL.Bool,
    'masterVolume' : IDL.Float64,
    'killStreaks' : IDL.Bool,
    'sfxVolume' : IDL.Float64,
    'musicVolume' : IDL.Float64,
    'particleQuality' : IDL.Text,
    'chatNotifications' : IDL.Bool,
    'damageNumbers' : IDL.Bool,
    'ambientSound' : IDL.Bool,
    'autoPickupGold' : IDL.Bool,
    'respawnCity' : IDL.Text,
    'smoothCamera' : IDL.Bool,
  });
  const PlayerMessages = IDL.Record({
    'principal' : IDL.Principal,
    'username' : Username,
    'messages' : IDL.Vec(ChatMessage),
  });
  const TradeLogEntry = IDL.Record({
    'offeredItemIds' : IDL.Vec(IDL.Text),
    'goldChange' : IDL.Int,
    'tradeId' : IDL.Text,
    'timestamp' : Timestamp,
    'receivedItemIds' : IDL.Vec(IDL.Text),
    'counterpartyUsername' : IDL.Text,
  });
  const WhisperMessage = IDL.Record({
    'to' : IDL.Text,
    'from' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const TradeOffer = IDL.Record({
    'principal' : IDL.Principal,
    'goldAmount' : IDL.Nat,
    'accepted' : IDL.Bool,
    'itemIds' : IDL.Vec(IDL.Text),
  });
  const TradeSession = IDL.Record({
    'completedAt' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'offerA' : TradeOffer,
    'offerB' : TradeOffer,
    'tradeId' : IDL.Text,
  });
  
  return IDL.Service({
    'acceptPartyInvite' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : PartyData, 'err' : IDL.Text })],
        [],
      ),
    'acceptTrade' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
    'applyPvpDamage' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Principal],
        [
          IDL.Record({
            'died' : IDL.Bool,
            'goldDropped' : IDL.Nat,
            'newHp' : IDL.Int,
            'xpLost' : IDL.Nat,
          }),
        ],
        [],
      ),
    'cancelTrade' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'checkNicknameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'claimDailyBonus' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'collectBounty' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'collectDroppedGold' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'completeQuest' : IDL.Func([IDL.Text], [], []),
    'createGuild' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : GuildData, 'err' : IDL.Text })],
        [],
      ),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(PlayerProfile)], ['query']),
    'getAllPlayers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, PlayerState))],
        ['query'],
      ),
    'getCharacterCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getDiscoveredZones' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getFriendsList' : IDL.Func([], [IDL.Vec(FriendRecord)], []),
    'getGuild' : IDL.Func([IDL.Text], [IDL.Opt(GuildData)], ['query']),
    'getGuildByName' : IDL.Func([IDL.Text], [IDL.Opt(GuildData)], ['query']),
    'getGuildLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(GuildLeaderboardEntry)],
        ['query'],
      ),
    'getGuildMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(GuildChatMessage), 'err' : IDL.Text })],
        [],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getLeaderboardByLevelKills' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMyParty' : IDL.Func([], [IDL.Opt(PartyData)], []),
    'getOnlinePlayerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getPendingPartyInvite' : IDL.Func([], [IDL.Opt(PartyInvite)], []),
    'getPlayerAchievements' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getPlayerSettings' : IDL.Func([], [IDL.Opt(PlayerSettings)], []),
    'getRecentMessages' : IDL.Func([], [IDL.Vec(PlayerMessages)], ['query']),
    'getSkillTree' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'getTradeLog' : IDL.Func([], [IDL.Vec(TradeLogEntry)], []),
    'getWhispers' : IDL.Func([], [IDL.Vec(WhisperMessage)], []),
    'grantAchievement' : IDL.Func([IDL.Text], [], []),
    'grantTitle' : IDL.Func([IDL.Text], [], []),
    'initiateTrade' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : TradeSession, 'err' : IDL.Text })],
        [],
      ),
    'inviteToParty' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'leaveParty' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'loadPlayer' : IDL.Func([Username, CharacterClass], [PlayerState], []),
    'recordAttack' : IDL.Func([], [], []),
    'recordCraftedItem' : IDL.Func([IDL.Text], [], []),
    'recordMonsterKill' : IDL.Func([], [], []),
    'recordPlayerDeath' : IDL.Func([], [], []),
    'recordPvpKill' : IDL.Func(
        [],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'addedBounty' : IDL.Nat,
            'becameWanted' : IDL.Nat,
          }),
        ],
        [],
      ),
    'registerNickname' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeGuild' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'resetBountyOnSafeZone' : IDL.Func([], [], []),
    'saveActiveTitle' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
    'saveDiscoveredZones' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveEmote' : IDL.Func([EmoteType], [], []),
    'saveFriendsList' : IDL.Func([IDL.Vec(FriendRecord)], [], []),
    'saveGuildMembership' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'savePlayerAchievements' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'savePlayerClass' : IDL.Func([CharacterClass], [], []),
    'savePlayerCoins' : IDL.Func([IDL.Nat], [], []),
    'savePlayerEquipment' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'savePlayerHP' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'savePlayerInventory' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'savePlayerOutfit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'savePlayerPosition' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'savePlayerSettings' : IDL.Func([PlayerSettings], [], []),
    'savePlayerTitles' : IDL.Func(
        [IDL.Vec(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'savePlayerXP' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'savePotionCount' : IDL.Func([IDL.Nat], [], []),
    'saveQuestProgress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveRespawnCity' : IDL.Func([IDL.Text], [], []),
    'saveSkillTree' : IDL.Func([IDL.Text], [], []),
    'saveZoneAndPlaytime' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'sendChatMessage' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendGuildChat' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'sendWhisper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'unlockAchievement' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateGuildMembers' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text))],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateTradeOffer' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };