/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CharacterClass = string;
export interface ChatMessage { 'text' : string, 'timestamp' : Timestamp }
export type EmoteType = { 'heart' : null } |
  { 'confused' : null } |
  { 'wave' : null } |
  { 'thumbsUp' : null };
export interface FriendRecord {
  'status' : FriendStatus,
  'username' : string,
  'principalId' : string,
}
export type FriendStatus = { 'pending' : null } |
  { 'accepted' : null };
export interface GuildChatMessage {
  'text' : string,
  'senderUsername' : string,
  'senderPrincipal' : string,
  'timestamp' : Timestamp,
}
export interface GuildData {
  'members' : Array<[Principal, string]>,
  'leaderId' : Principal,
  'guildId' : string,
  'chatMessages' : Array<GuildChatMessage>,
  'name' : string,
  'createdAt' : Timestamp,
  'maxMembers' : bigint,
}
export interface GuildLeaderboardEntry {
  'guildId' : string,
  'name' : string,
  'memberCount' : bigint,
  'totalMemberLevels' : bigint,
  'totalKills' : bigint,
}
export interface LeaderboardEntry {
  'activityScore' : bigint,
  'characterClass' : string,
  'username' : Username,
  'pvpKills' : bigint,
  'level' : bigint,
  'monsterKills' : bigint,
  'lastActive' : Timestamp,
}
export interface PartyData {
  'members' : Array<PartyMember>,
  'leaderId' : Principal,
  'createdAt' : Timestamp,
  'partyId' : string,
}
export interface PartyInvite {
  'toPrincipal' : Principal,
  'fromPrincipal' : string,
  'timestamp' : Timestamp,
  'fromUsername' : string,
  'partyId' : string,
}
export interface PartyMember { 'principal' : Principal, 'username' : string }
export interface PlayerMessages {
  'principal' : Principal,
  'username' : Username,
  'messages' : Array<ChatMessage>,
}
export interface PlayerProfile {
  'username' : Username,
  'class' : string,
  'coins' : bigint,
  'equippedItems' : Array<string>,
  'deaths' : bigint,
  'activeTitle' : string,
  'pvpKills' : bigint,
  'level' : bigint,
  'totalPlaytime' : bigint,
  'monsterKills' : bigint,
  'lastZone' : string,
}
export interface PlayerSettings {
  'weatherEffects' : boolean,
  'dayNightCycle' : boolean,
  'masterVolume' : number,
  'killStreaks' : boolean,
  'sfxVolume' : number,
  'musicVolume' : number,
  'particleQuality' : string,
  'chatNotifications' : boolean,
  'damageNumbers' : boolean,
  'ambientSound' : boolean,
  'autoPickupGold' : boolean,
  'respawnCity' : string,
  'smoothCamera' : boolean,
}
export interface PlayerState {
  'x' : bigint,
  'y' : bigint,
  'hp' : bigint,
  'mp' : bigint,
  'xp' : bigint,
  'maxHp' : bigint,
  'maxMp' : bigint,
  'questProgress' : [] | [bigint],
  'guildRank' : [] | [string],
  'isWanted' : [] | [boolean],
  'activityScore' : bigint,
  'playerTitles' : [] | [Array<string>],
  'username' : Username,
  'lastDailyBonus' : [] | [Timestamp],
  'bountyAmount' : [] | [bigint],
  'inventoryItems' : Array<string>,
  'equippedOffhand' : [] | [string],
  'selectedClass' : CharacterClass,
  'guildId' : [] | [string],
  'chatMessages' : Array<ChatMessage>,
  'coins' : bigint,
  'activeQuestId' : [] | [string],
  'skillTree' : [] | [string],
  'friendsList' : [] | [Array<string>],
  'craftedItems' : [] | [Array<string>],
  'deaths' : [] | [bigint],
  'activeTitle' : [] | [string],
  'pvpKills' : bigint,
  'outfitColor' : string,
  'level' : bigint,
  'discoveredZones' : [] | [Array<string>],
  'achievements' : Array<string>,
  'totalPlaytime' : [] | [bigint],
  'emoteTimestamp' : Timestamp,
  'monsterKills' : bigint,
  'skillPoints' : [] | [bigint],
  'completedQuestIds' : Array<string>,
  'outfitStyle' : string,
  'potionCount' : [] | [bigint],
  'currentEmote' : [] | [EmoteType],
  'equippedArmor' : [] | [string],
  'pvpKillsSession' : [] | [bigint],
  'characterId' : bigint,
  'hairColor' : string,
  'lastActive' : Timestamp,
  'kills' : bigint,
  'respawnCity' : [] | [string],
  'lastZone' : [] | [string],
  'equippedWeapon' : [] | [string],
  'partyId' : [] | [string],
}
export type Timestamp = bigint;
export interface TradeLogEntry {
  'offeredItemIds' : Array<string>,
  'goldChange' : bigint,
  'tradeId' : string,
  'timestamp' : Timestamp,
  'receivedItemIds' : Array<string>,
  'counterpartyUsername' : string,
}
export interface TradeOffer {
  'principal' : Principal,
  'goldAmount' : bigint,
  'accepted' : boolean,
  'itemIds' : Array<string>,
}
export interface TradeSession {
  'completedAt' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'offerA' : TradeOffer,
  'offerB' : TradeOffer,
  'tradeId' : string,
}
export type Username = string;
export interface WhisperMessage {
  'to' : string,
  'from' : string,
  'text' : string,
  'timestamp' : Timestamp,
}
export interface _SERVICE {
  'acceptPartyInvite' : ActorMethod<
    [string],
    { 'ok' : PartyData } |
      { 'err' : string }
  >,
  'acceptTrade' : ActorMethod<
    [string],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  /**
   * / Parties: partyId → PartyData
   */
  'applyPvpDamage' : ActorMethod<
    [Principal, bigint, Principal],
    {
      'died' : boolean,
      'goldDropped' : bigint,
      'newHp' : bigint,
      'xpLost' : bigint,
    }
  >,
  'cancelTrade' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'checkNicknameAvailable' : ActorMethod<[string], boolean>,
  'claimDailyBonus' : ActorMethod<[], { 'ok' : bigint } | { 'err' : string }>,
  'collectBounty' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'collectDroppedGold' : ActorMethod<[bigint], boolean>,
  'completeQuest' : ActorMethod<[string], undefined>,
  'createGuild' : ActorMethod<
    [string],
    { 'ok' : GuildData } |
      { 'err' : string }
  >,
  'getAllCharacters' : ActorMethod<[], Array<PlayerProfile>>,
  'getAllPlayers' : ActorMethod<[], Array<[Principal, PlayerState]>>,
  'getCharacterCount' : ActorMethod<[], bigint>,
  'getDiscoveredZones' : ActorMethod<[], Array<string>>,
  'getFriendsList' : ActorMethod<[], Array<FriendRecord>>,
  /**
   * / Social: whisper inbox keyed by Principal → [WhisperMessage]
   */
  'getGuild' : ActorMethod<[string], [] | [GuildData]>,
  /**
   * / Guild names index: lowercase name → guildId for uniqueness
   */
  'getGuildByName' : ActorMethod<[string], [] | [GuildData]>,
  'getGuildLeaderboard' : ActorMethod<[], Array<GuildLeaderboardEntry>>,
  'getGuildMessages' : ActorMethod<
    [string],
    { 'ok' : Array<GuildChatMessage> } |
      { 'err' : string }
  >,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  /**
   * / Lowercased nickname -> owner Principal for global uniqueness enforcement
   */
  'getLeaderboardByLevelKills' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyParty' : ActorMethod<[], [] | [PartyData]>,
  'getOnlinePlayerCount' : ActorMethod<[], bigint>,
  'getPendingPartyInvite' : ActorMethod<[], [] | [PartyInvite]>,
  'getPlayerAchievements' : ActorMethod<[], Array<string>>,
  'getPlayerSettings' : ActorMethod<[], [] | [PlayerSettings]>,
  'getRecentMessages' : ActorMethod<[], Array<PlayerMessages>>,
  'getSkillTree' : ActorMethod<[], [] | [string]>,
  'getTradeLog' : ActorMethod<[], Array<TradeLogEntry>>,
  /**
   * / Zone discoveries: Principal → [ZoneId]
   */
  'getWhispers' : ActorMethod<[], Array<WhisperMessage>>,
  'grantAchievement' : ActorMethod<[string], undefined>,
  'grantTitle' : ActorMethod<[string], undefined>,
  'initiateTrade' : ActorMethod<
    [string],
    { 'ok' : TradeSession } |
      { 'err' : string }
  >,
  'inviteToParty' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'leaveParty' : ActorMethod<[], { 'ok' : null } | { 'err' : string }>,
  'loadPlayer' : ActorMethod<[Username, CharacterClass], PlayerState>,
  'recordAttack' : ActorMethod<[], undefined>,
  'recordCraftedItem' : ActorMethod<[string], undefined>,
  'recordMonsterKill' : ActorMethod<[], undefined>,
  'recordPlayerDeath' : ActorMethod<[], undefined>,
  'recordPvpKill' : ActorMethod<
    [],
    { 'ok' : null } |
      { 'addedBounty' : bigint } |
      { 'becameWanted' : bigint }
  >,
  'registerNickname' : ActorMethod<[string], boolean>,
  'removeGuild' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'resetBountyOnSafeZone' : ActorMethod<[], undefined>,
  'saveActiveTitle' : ActorMethod<[[] | [string]], undefined>,
  'saveDiscoveredZones' : ActorMethod<[Array<string>], undefined>,
  'saveEmote' : ActorMethod<[EmoteType], undefined>,
  'saveFriendsList' : ActorMethod<[Array<FriendRecord>], undefined>,
  'saveGuildMembership' : ActorMethod<
    [[] | [string], [] | [string]],
    undefined
  >,
  'savePlayerAchievements' : ActorMethod<[Array<string>], undefined>,
  'savePlayerClass' : ActorMethod<[CharacterClass], undefined>,
  'savePlayerCoins' : ActorMethod<[bigint], undefined>,
  'savePlayerEquipment' : ActorMethod<
    [[] | [string], [] | [string], [] | [string]],
    undefined
  >,
  'savePlayerHP' : ActorMethod<[bigint, bigint], undefined>,
  'savePlayerInventory' : ActorMethod<[Array<string>], undefined>,
  'savePlayerOutfit' : ActorMethod<[string, string, [] | [string]], undefined>,
  'savePlayerPosition' : ActorMethod<[bigint, bigint], undefined>,
  'savePlayerSettings' : ActorMethod<[PlayerSettings], undefined>,
  'savePlayerTitles' : ActorMethod<[Array<string>, [] | [string]], undefined>,
  'savePlayerXP' : ActorMethod<[bigint, bigint], undefined>,
  'savePotionCount' : ActorMethod<[bigint], undefined>,
  'saveQuestProgress' : ActorMethod<[string, bigint], undefined>,
  'saveRespawnCity' : ActorMethod<[string], undefined>,
  'saveSkillTree' : ActorMethod<[string], undefined>,
  'saveZoneAndPlaytime' : ActorMethod<[string, bigint], undefined>,
  'sendChatMessage' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendGuildChat' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'sendWhisper' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'unlockAchievement' : ActorMethod<[string], boolean>,
  /**
   * / Zone discoveries: Principal → [ZoneId]
   */
  'updateGuildMembers' : ActorMethod<
    [string, Array<[Principal, string]>],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateTradeOffer' : ActorMethod<
    [string, Array<string>, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];