/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PartyInvite {
    toPrincipal: Principal;
    fromPrincipal: string;
    timestamp: Timestamp;
    fromUsername: string;
    partyId: string;
}
export interface TradeOffer {
    principal: Principal;
    goldAmount: bigint;
    accepted: boolean;
    itemIds: Array<string>;
}
export type Timestamp = bigint;
export interface PartyData {
    members: Array<PartyMember>;
    leaderId: Principal;
    createdAt: Timestamp;
    partyId: string;
}
export interface LeaderboardEntry {
    activityScore: bigint;
    characterClass: string;
    username: Username;
    pvpKills: bigint;
    level: bigint;
    monsterKills: bigint;
    lastActive: Timestamp;
}
export interface GuildLeaderboardEntry {
    guildId: string;
    name: string;
    memberCount: bigint;
    totalMemberLevels: bigint;
    totalKills: bigint;
}
export interface PlayerProfile {
    username: Username;
    class: string;
    coins: bigint;
    equippedItems: Array<string>;
    deaths: bigint;
    activeTitle: string;
    pvpKills: bigint;
    level: bigint;
    totalPlaytime: bigint;
    monsterKills: bigint;
    lastZone: string;
}
export interface GuildData {
    members: Array<[Principal, string]>;
    leaderId: Principal;
    guildId: string;
    chatMessages: Array<GuildChatMessage>;
    name: string;
    createdAt: Timestamp;
    maxMembers: bigint;
}
export interface PlayerMessages {
    principal: Principal;
    username: Username;
    messages: Array<ChatMessage>;
}
export interface WhisperMessage {
    to: string;
    from: string;
    text: string;
    timestamp: Timestamp;
}
export interface TradeSession {
    completedAt?: Timestamp;
    createdAt: Timestamp;
    offerA: TradeOffer;
    offerB: TradeOffer;
    tradeId: string;
}
export interface PartyMember {
    principal: Principal;
    username: string;
}
export interface TradeLogEntry {
    offeredItemIds: Array<string>;
    goldChange: bigint;
    tradeId: string;
    timestamp: Timestamp;
    receivedItemIds: Array<string>;
    counterpartyUsername: string;
}
export interface PlayerState {
    x: bigint;
    y: bigint;
    hp: bigint;
    mp: bigint;
    xp: bigint;
    maxHp: bigint;
    maxMp: bigint;
    questProgress?: bigint;
    guildRank?: string;
    isWanted?: boolean;
    activityScore: bigint;
    playerTitles?: Array<string>;
    username: Username;
    lastDailyBonus?: Timestamp;
    bountyAmount?: bigint;
    inventoryItems: Array<string>;
    equippedOffhand?: string;
    selectedClass: CharacterClass;
    guildId?: string;
    chatMessages: Array<ChatMessage>;
    coins: bigint;
    activeQuestId?: string;
    skillTree?: string;
    friendsList?: Array<string>;
    craftedItems?: Array<string>;
    deaths?: bigint;
    activeTitle?: string;
    pvpKills: bigint;
    outfitColor: string;
    level: bigint;
    discoveredZones?: Array<string>;
    achievements: Array<string>;
    totalPlaytime?: bigint;
    emoteTimestamp: Timestamp;
    monsterKills: bigint;
    skillPoints?: bigint;
    completedQuestIds: Array<string>;
    outfitStyle: string;
    potionCount?: bigint;
    currentEmote?: EmoteType;
    equippedArmor?: string;
    pvpKillsSession?: bigint;
    characterId: bigint;
    hairColor: string;
    lastActive: Timestamp;
    kills: bigint;
    respawnCity?: string;
    lastZone?: string;
    equippedWeapon?: string;
    partyId?: string;
}
export interface FriendRecord {
    status: FriendStatus;
    username: string;
    principalId: string;
}
export interface ChatMessage {
    text: string;
    timestamp: Timestamp;
}
export type Username = string;
export interface PlayerSettings {
    weatherEffects: boolean;
    dayNightCycle: boolean;
    masterVolume: number;
    killStreaks: boolean;
    sfxVolume: number;
    musicVolume: number;
    particleQuality: string;
    chatNotifications: boolean;
    damageNumbers: boolean;
    ambientSound: boolean;
    autoPickupGold: boolean;
    respawnCity: string;
    smoothCamera: boolean;
}
export type CharacterClass = string;
export interface GuildChatMessage {
    text: string;
    senderUsername: string;
    senderPrincipal: string;
    timestamp: Timestamp;
}
export enum EmoteType {
    heart = "heart",
    confused = "confused",
    wave = "wave",
    thumbsUp = "thumbsUp"
}
export enum FriendStatus {
    pending = "pending",
    accepted = "accepted"
}
export interface backendInterface {
    acceptPartyInvite(acceptingUsername: string): Promise<{
        __kind__: "ok";
        ok: PartyData;
    } | {
        __kind__: "err";
        err: string;
    }>;
    acceptTrade(tradeId: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }>;
    /**
     * / Parties: partyId → PartyData
     */
    applyPvpDamage(victimPrincipal: Principal, damage: bigint, attackerPrincipal: Principal): Promise<{
        died: boolean;
        goldDropped: bigint;
        newHp: bigint;
        xpLost: bigint;
    }>;
    cancelTrade(tradeId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    checkNicknameAvailable(name: string): Promise<boolean>;
    claimDailyBonus(): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    collectBounty(wantedPrincipalText: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    collectDroppedGold(amount: bigint): Promise<boolean>;
    completeQuest(questId: string): Promise<void>;
    createGuild(name: string): Promise<{
        __kind__: "ok";
        ok: GuildData;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getAllCharacters(): Promise<Array<PlayerProfile>>;
    getAllPlayers(): Promise<Array<[Principal, PlayerState]>>;
    getCharacterCount(): Promise<bigint>;
    getDiscoveredZones(): Promise<Array<string>>;
    getFriendsList(): Promise<Array<FriendRecord>>;
    /**
     * / Social: whisper inbox keyed by Principal → [WhisperMessage]
     */
    getGuild(guildId: string): Promise<GuildData | null>;
    /**
     * / Guild names index: lowercase name → guildId for uniqueness
     */
    getGuildByName(name: string): Promise<GuildData | null>;
    getGuildLeaderboard(): Promise<Array<GuildLeaderboardEntry>>;
    getGuildMessages(guildId: string): Promise<{
        __kind__: "ok";
        ok: Array<GuildChatMessage>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    /**
     * / Lowercased nickname -> owner Principal for global uniqueness enforcement
     */
    getLeaderboardByLevelKills(): Promise<Array<LeaderboardEntry>>;
    getMyParty(): Promise<PartyData | null>;
    getOnlinePlayerCount(): Promise<bigint>;
    getPendingPartyInvite(): Promise<PartyInvite | null>;
    getPlayerAchievements(): Promise<Array<string>>;
    getPlayerSettings(): Promise<PlayerSettings | null>;
    getRecentMessages(): Promise<Array<PlayerMessages>>;
    getSkillTree(): Promise<string | null>;
    getTradeLog(): Promise<Array<TradeLogEntry>>;
    /**
     * / Zone discoveries: Principal → [ZoneId]
     */
    getWhispers(): Promise<Array<WhisperMessage>>;
    grantAchievement(achievementId: string): Promise<void>;
    grantTitle(titleId: string): Promise<void>;
    initiateTrade(counterpartyPrincipalText: string): Promise<{
        __kind__: "ok";
        ok: TradeSession;
    } | {
        __kind__: "err";
        err: string;
    }>;
    inviteToParty(targetPrincipalText: string, callerUsername: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    leaveParty(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    loadPlayer(username: Username, selectedClass: CharacterClass): Promise<PlayerState>;
    recordAttack(): Promise<void>;
    recordCraftedItem(itemId: string): Promise<void>;
    recordMonsterKill(): Promise<void>;
    recordPlayerDeath(): Promise<void>;
    recordPvpKill(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "addedBounty";
        addedBounty: bigint;
    } | {
        __kind__: "becameWanted";
        becameWanted: bigint;
    }>;
    registerNickname(name: string): Promise<boolean>;
    removeGuild(guildId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetBountyOnSafeZone(): Promise<void>;
    saveActiveTitle(title: string | null): Promise<void>;
    saveDiscoveredZones(zones: Array<string>): Promise<void>;
    saveEmote(emote: EmoteType): Promise<void>;
    saveFriendsList(list: Array<FriendRecord>): Promise<void>;
    saveGuildMembership(guildId: string | null, guildRank: string | null): Promise<void>;
    savePlayerAchievements(achievements: Array<string>): Promise<void>;
    savePlayerClass(selectedClass: CharacterClass): Promise<void>;
    savePlayerCoins(coins: bigint): Promise<void>;
    savePlayerEquipment(weapon: string | null, armor: string | null, offhand: string | null): Promise<void>;
    savePlayerHP(hp: bigint, mp: bigint): Promise<void>;
    savePlayerInventory(items: Array<string>): Promise<void>;
    savePlayerOutfit(color: string, style: string, hairColor: string | null): Promise<void>;
    savePlayerPosition(x: bigint, y: bigint): Promise<void>;
    savePlayerSettings(s: PlayerSettings): Promise<void>;
    savePlayerTitles(titles: Array<string>, activeTitle: string | null): Promise<void>;
    savePlayerXP(xp: bigint, level: bigint): Promise<void>;
    savePotionCount(count: bigint): Promise<void>;
    saveQuestProgress(questId: string, progress: bigint): Promise<void>;
    saveRespawnCity(cityId: string): Promise<void>;
    saveSkillTree(json: string): Promise<void>;
    saveZoneAndPlaytime(zone: string, additionalSeconds: bigint): Promise<void>;
    sendChatMessage(text: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendGuildChat(guildId: string, senderUsername: string, text: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendWhisper(recipientPrincipalText: string, recipientUsername: string, senderUsername: string, text: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    unlockAchievement(achievementId: string): Promise<boolean>;
    /**
     * / Zone discoveries: Principal → [ZoneId]
     */
    updateGuildMembers(guildId: string, members: Array<[Principal, string]>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateTradeOffer(tradeId: string, itemIds: Array<string>, goldAmount: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { CharacterClass as _CharacterClass, ChatMessage as _ChatMessage, EmoteType as _EmoteType, FriendRecord as _FriendRecord, FriendStatus as _FriendStatus, GuildChatMessage as _GuildChatMessage, GuildData as _GuildData, PartyData as _PartyData, PartyInvite as _PartyInvite, PlayerSettings as _PlayerSettings, PlayerState as _PlayerState, Timestamp as _Timestamp, TradeOffer as _TradeOffer, TradeSession as _TradeSession, Username as _Username } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptPartyInvite(arg0: string): Promise<{
        __kind__: "ok";
        ok: PartyData;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptPartyInvite(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptPartyInvite(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async acceptTrade(arg0: string): Promise<{
        __kind__: "ok";
        ok: boolean;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptTrade(arg0);
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptTrade(arg0);
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async applyPvpDamage(arg0: Principal, arg1: bigint, arg2: Principal): Promise<{
        died: boolean;
        goldDropped: bigint;
        newHp: bigint;
        xpLost: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.applyPvpDamage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyPvpDamage(arg0, arg1, arg2);
            return result;
        }
    }
    async cancelTrade(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelTrade(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelTrade(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkNicknameAvailable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkNicknameAvailable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkNicknameAvailable(arg0);
            return result;
        }
    }
    async claimDailyBonus(): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyBonus();
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyBonus();
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async collectBounty(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.collectBounty(arg0);
                return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.collectBounty(arg0);
            return from_candid_variant_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async collectDroppedGold(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.collectDroppedGold(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.collectDroppedGold(arg0);
            return result;
        }
    }
    async completeQuest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeQuest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeQuest(arg0);
            return result;
        }
    }
    async createGuild(arg0: string): Promise<{
        __kind__: "ok";
        ok: GuildData;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createGuild(arg0);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGuild(arg0);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCharacters(): Promise<Array<PlayerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCharacters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCharacters();
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<[Principal, PlayerState]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacterCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacterCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacterCount();
            return result;
        }
    }
    async getDiscoveredZones(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiscoveredZones();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiscoveredZones();
            return result;
        }
    }
    async getFriendsList(): Promise<Array<FriendRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendsList();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendsList();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuild(arg0: string): Promise<GuildData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuild(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuild(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuildByName(arg0: string): Promise<GuildData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuildByName(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuildByName(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuildLeaderboard(): Promise<Array<GuildLeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuildLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuildLeaderboard();
            return result;
        }
    }
    async getGuildMessages(arg0: string): Promise<{
        __kind__: "ok";
        ok: Array<GuildChatMessage>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuildMessages(arg0);
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuildMessages(arg0);
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getLeaderboardByLevelKills(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboardByLevelKills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboardByLevelKills();
            return result;
        }
    }
    async getMyParty(): Promise<PartyData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyParty();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyParty();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnlinePlayerCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnlinePlayerCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnlinePlayerCount();
            return result;
        }
    }
    async getPendingPartyInvite(): Promise<PartyInvite | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPartyInvite();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPartyInvite();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayerAchievements(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerAchievements();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerAchievements();
            return result;
        }
    }
    async getPlayerSettings(): Promise<PlayerSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerSettings();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerSettings();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentMessages(): Promise<Array<PlayerMessages>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentMessages();
            return result;
        }
    }
    async getSkillTree(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillTree();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillTree();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTradeLog(): Promise<Array<TradeLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeLog();
            return result;
        }
    }
    async getWhispers(): Promise<Array<WhisperMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhispers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhispers();
            return result;
        }
    }
    async grantAchievement(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantAchievement(arg0);
            return result;
        }
    }
    async grantTitle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantTitle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantTitle(arg0);
            return result;
        }
    }
    async initiateTrade(arg0: string): Promise<{
        __kind__: "ok";
        ok: TradeSession;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.initiateTrade(arg0);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initiateTrade(arg0);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async inviteToParty(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.inviteToParty(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inviteToParty(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async leaveParty(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveParty();
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveParty();
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async loadPlayer(arg0: Username, arg1: CharacterClass): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.loadPlayer(arg0, arg1);
                return from_candid_PlayerState_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadPlayer(arg0, arg1);
            return from_candid_PlayerState_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordAttack(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordAttack();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordAttack();
            return result;
        }
    }
    async recordCraftedItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordCraftedItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordCraftedItem(arg0);
            return result;
        }
    }
    async recordMonsterKill(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordMonsterKill();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordMonsterKill();
            return result;
        }
    }
    async recordPlayerDeath(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPlayerDeath();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPlayerDeath();
            return result;
        }
    }
    async recordPvpKill(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "addedBounty";
        addedBounty: bigint;
    } | {
        __kind__: "becameWanted";
        becameWanted: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPvpKill();
                return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPvpKill();
            return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerNickname(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.registerNickname(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerNickname(arg0);
            return result;
        }
    }
    async removeGuild(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeGuild(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeGuild(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetBountyOnSafeZone(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetBountyOnSafeZone();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetBountyOnSafeZone();
            return result;
        }
    }
    async saveActiveTitle(arg0: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveActiveTitle(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveActiveTitle(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveDiscoveredZones(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDiscoveredZones(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDiscoveredZones(arg0);
            return result;
        }
    }
    async saveEmote(arg0: EmoteType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmote(to_candid_EmoteType_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmote(to_candid_EmoteType_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveFriendsList(arg0: Array<FriendRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFriendsList(to_candid_vec_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFriendsList(to_candid_vec_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveGuildMembership(arg0: string | null, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGuildMembership(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGuildMembership(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async savePlayerAchievements(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerAchievements(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerAchievements(arg0);
            return result;
        }
    }
    async savePlayerClass(arg0: CharacterClass): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerClass(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerClass(arg0);
            return result;
        }
    }
    async savePlayerCoins(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerCoins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerCoins(arg0);
            return result;
        }
    }
    async savePlayerEquipment(arg0: string | null, arg1: string | null, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerEquipment(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerEquipment(to_candid_opt_n32(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async savePlayerHP(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerHP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerHP(arg0, arg1);
            return result;
        }
    }
    async savePlayerInventory(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerInventory(arg0);
            return result;
        }
    }
    async savePlayerOutfit(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerOutfit(arg0, arg1, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerOutfit(arg0, arg1, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async savePlayerPosition(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerPosition(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerPosition(arg0, arg1);
            return result;
        }
    }
    async savePlayerSettings(arg0: PlayerSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerSettings(arg0);
            return result;
        }
    }
    async savePlayerTitles(arg0: Array<string>, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerTitles(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerTitles(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async savePlayerXP(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePlayerXP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePlayerXP(arg0, arg1);
            return result;
        }
    }
    async savePotionCount(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.savePotionCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePotionCount(arg0);
            return result;
        }
    }
    async saveQuestProgress(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuestProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuestProgress(arg0, arg1);
            return result;
        }
    }
    async saveRespawnCity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveRespawnCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveRespawnCity(arg0);
            return result;
        }
    }
    async saveSkillTree(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSkillTree(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSkillTree(arg0);
            return result;
        }
    }
    async saveZoneAndPlaytime(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveZoneAndPlaytime(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveZoneAndPlaytime(arg0, arg1);
            return result;
        }
    }
    async sendChatMessage(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendGuildChat(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendGuildChat(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendGuildChat(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendWhisper(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.sendWhisper(arg0, arg1, arg2, arg3);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendWhisper(arg0, arg1, arg2, arg3);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async unlockAchievement(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unlockAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlockAchievement(arg0);
            return result;
        }
    }
    async updateGuildMembers(arg0: string, arg1: Array<[Principal, string]>): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGuildMembers(arg0, arg1);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGuildMembers(arg0, arg1);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTradeOffer(arg0: string, arg1: Array<string>, arg2: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTradeOffer(arg0, arg1, arg2);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTradeOffer(arg0, arg1, arg2);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_EmoteType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmoteType): EmoteType {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_FriendRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendRecord): FriendRecord {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_FriendStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendStatus): FriendStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PlayerState_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerState): PlayerState {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TradeSession_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeSession): TradeSession {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmoteType]): EmoteType | null {
    return value.length === 0 ? null : from_candid_EmoteType_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GuildData]): GuildData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PartyData]): PartyData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PartyInvite]): PartyInvite | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerSettings]): PlayerSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _FriendStatus;
    username: string;
    principalId: string;
}): {
    status: FriendStatus;
    username: string;
    principalId: string;
} {
    return {
        status: from_candid_FriendStatus_n21(_uploadFile, _downloadFile, value.status),
        username: value.username,
        principalId: value.principalId
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: [] | [_Timestamp];
    createdAt: _Timestamp;
    offerA: _TradeOffer;
    offerB: _TradeOffer;
    tradeId: string;
}): {
    completedAt?: Timestamp;
    createdAt: Timestamp;
    offerA: TradeOffer;
    offerB: TradeOffer;
    tradeId: string;
} {
    return {
        completedAt: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.completedAt)),
        createdAt: value.createdAt,
        offerA: value.offerA,
        offerB: value.offerB,
        tradeId: value.tradeId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    x: bigint;
    y: bigint;
    hp: bigint;
    mp: bigint;
    xp: bigint;
    maxHp: bigint;
    maxMp: bigint;
    questProgress: [] | [bigint];
    guildRank: [] | [string];
    isWanted: [] | [boolean];
    activityScore: bigint;
    playerTitles: [] | [Array<string>];
    username: _Username;
    lastDailyBonus: [] | [_Timestamp];
    bountyAmount: [] | [bigint];
    inventoryItems: Array<string>;
    equippedOffhand: [] | [string];
    selectedClass: _CharacterClass;
    guildId: [] | [string];
    chatMessages: Array<_ChatMessage>;
    coins: bigint;
    activeQuestId: [] | [string];
    skillTree: [] | [string];
    friendsList: [] | [Array<string>];
    craftedItems: [] | [Array<string>];
    deaths: [] | [bigint];
    activeTitle: [] | [string];
    pvpKills: bigint;
    outfitColor: string;
    level: bigint;
    discoveredZones: [] | [Array<string>];
    achievements: Array<string>;
    totalPlaytime: [] | [bigint];
    emoteTimestamp: _Timestamp;
    monsterKills: bigint;
    skillPoints: [] | [bigint];
    completedQuestIds: Array<string>;
    outfitStyle: string;
    potionCount: [] | [bigint];
    currentEmote: [] | [_EmoteType];
    equippedArmor: [] | [string];
    pvpKillsSession: [] | [bigint];
    characterId: bigint;
    hairColor: string;
    lastActive: _Timestamp;
    kills: bigint;
    respawnCity: [] | [string];
    lastZone: [] | [string];
    equippedWeapon: [] | [string];
    partyId: [] | [string];
}): {
    x: bigint;
    y: bigint;
    hp: bigint;
    mp: bigint;
    xp: bigint;
    maxHp: bigint;
    maxMp: bigint;
    questProgress?: bigint;
    guildRank?: string;
    isWanted?: boolean;
    activityScore: bigint;
    playerTitles?: Array<string>;
    username: Username;
    lastDailyBonus?: Timestamp;
    bountyAmount?: bigint;
    inventoryItems: Array<string>;
    equippedOffhand?: string;
    selectedClass: CharacterClass;
    guildId?: string;
    chatMessages: Array<ChatMessage>;
    coins: bigint;
    activeQuestId?: string;
    skillTree?: string;
    friendsList?: Array<string>;
    craftedItems?: Array<string>;
    deaths?: bigint;
    activeTitle?: string;
    pvpKills: bigint;
    outfitColor: string;
    level: bigint;
    discoveredZones?: Array<string>;
    achievements: Array<string>;
    totalPlaytime?: bigint;
    emoteTimestamp: Timestamp;
    monsterKills: bigint;
    skillPoints?: bigint;
    completedQuestIds: Array<string>;
    outfitStyle: string;
    potionCount?: bigint;
    currentEmote?: EmoteType;
    equippedArmor?: string;
    pvpKillsSession?: bigint;
    characterId: bigint;
    hairColor: string;
    lastActive: Timestamp;
    kills: bigint;
    respawnCity?: string;
    lastZone?: string;
    equippedWeapon?: string;
    partyId?: string;
} {
    return {
        x: value.x,
        y: value.y,
        hp: value.hp,
        mp: value.mp,
        xp: value.xp,
        maxHp: value.maxHp,
        maxMp: value.maxMp,
        questProgress: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.questProgress)),
        guildRank: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.guildRank)),
        isWanted: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.isWanted)),
        activityScore: value.activityScore,
        playerTitles: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.playerTitles)),
        username: value.username,
        lastDailyBonus: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.lastDailyBonus)),
        bountyAmount: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.bountyAmount)),
        inventoryItems: value.inventoryItems,
        equippedOffhand: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.equippedOffhand)),
        selectedClass: value.selectedClass,
        guildId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.guildId)),
        chatMessages: value.chatMessages,
        coins: value.coins,
        activeQuestId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.activeQuestId)),
        skillTree: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.skillTree)),
        friendsList: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.friendsList)),
        craftedItems: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.craftedItems)),
        deaths: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deaths)),
        activeTitle: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.activeTitle)),
        pvpKills: value.pvpKills,
        outfitColor: value.outfitColor,
        level: value.level,
        discoveredZones: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.discoveredZones)),
        achievements: value.achievements,
        totalPlaytime: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.totalPlaytime)),
        emoteTimestamp: value.emoteTimestamp,
        monsterKills: value.monsterKills,
        skillPoints: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.skillPoints)),
        completedQuestIds: value.completedQuestIds,
        outfitStyle: value.outfitStyle,
        potionCount: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.potionCount)),
        currentEmote: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.currentEmote)),
        equippedArmor: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.equippedArmor)),
        pvpKillsSession: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.pvpKillsSession)),
        characterId: value.characterId,
        hairColor: value.hairColor,
        lastActive: value.lastActive,
        kills: value.kills,
        respawnCity: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.respawnCity)),
        lastZone: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.lastZone)),
        equippedWeapon: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.equippedWeapon)),
        partyId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.partyId))
    };
}
function from_candid_tuple_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _PlayerState]): [Principal, PlayerState] {
    return [
        value[0],
        from_candid_PlayerState_n8(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PartyData;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PartyData;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    heart: null;
} | {
    confused: null;
} | {
    wave: null;
} | {
    thumbsUp: null;
}): EmoteType {
    return "heart" in value ? EmoteType.heart : "confused" in value ? EmoteType.confused : "wave" in value ? EmoteType.wave : "thumbsUp" in value ? EmoteType.thumbsUp : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    accepted: null;
}): FriendStatus {
    return "pending" in value ? FriendStatus.pending : "accepted" in value ? FriendStatus.accepted : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_GuildChatMessage>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<GuildChatMessage>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TradeSession;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TradeSession;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TradeSession_n29(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    addedBounty: bigint;
} | {
    becameWanted: bigint;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "addedBounty";
    addedBounty: bigint;
} | {
    __kind__: "becameWanted";
    becameWanted: bigint;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "addedBounty" in value ? {
        __kind__: "addedBounty",
        addedBounty: value.addedBounty
    } : "becameWanted" in value ? {
        __kind__: "becameWanted",
        becameWanted: value.becameWanted
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GuildData;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GuildData;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendRecord>): Array<FriendRecord> {
    return value.map((x)=>from_candid_FriendRecord_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _PlayerState]>): Array<[Principal, PlayerState]> {
    return value.map((x)=>from_candid_tuple_n7(_uploadFile, _downloadFile, x));
}
function to_candid_EmoteType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmoteType): _EmoteType {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_FriendRecord_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FriendRecord): _FriendRecord {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_FriendStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FriendStatus): _FriendStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: FriendStatus;
    username: string;
    principalId: string;
}): {
    status: _FriendStatus;
    username: string;
    principalId: string;
} {
    return {
        status: to_candid_FriendStatus_n38(_uploadFile, _downloadFile, value.status),
        username: value.username,
        principalId: value.principalId
    };
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmoteType): {
    heart: null;
} | {
    confused: null;
} | {
    wave: null;
} | {
    thumbsUp: null;
} {
    return value == EmoteType.heart ? {
        heart: null
    } : value == EmoteType.confused ? {
        confused: null
    } : value == EmoteType.wave ? {
        wave: null
    } : value == EmoteType.thumbsUp ? {
        thumbsUp: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FriendStatus): {
    pending: null;
} | {
    accepted: null;
} {
    return value == FriendStatus.pending ? {
        pending: null
    } : value == FriendStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FriendRecord>): Array<_FriendRecord> {
    return value.map((x)=>to_candid_FriendRecord_n36(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
